# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_CAN_UART_REPLAY=y
CONFIG_CAN=y
CONFIG_SERIAL=y
CONFIG_LOG=y
CONFIG_CAN_RANDOM_TRAFFIC=y
CONFIG_CAN_RAND_TX_MSG_COUNT=3
CONFIG_CAN_RAND_TX_MSG0_ID=0x1
CONFIG_CAN_RAND_TX_MSG0_PERIOD_MS=3600000
CONFIG_CAN_RAND_TX_MSG1_ID=0x2
CONFIG_CAN_RAND_TX_MSG1_PERIOD_MS=3600000
CONFIG_CAN_RAND_TX_MSG2_ID=0x3
CONFIG_CAN_RAND_TX_MSG2_PERIOD_MS=3600000
